server {
    listen 80;
    server_name racked.dino.icu racked.hexagonical.xyz;

    root /usr/share/nginx/html;
    index index.html;

    # Handle /docs app
    location /docs {
        alias /usr/share/nginx/html/docs;
        try_files $uri $uri/ /docs/index.html;
    }

    # Handle root app
    location / {
        try_files $uri $uri/ /index.html;
    }
}