name: Build and Deploy
permissions: write-all
on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./racked-website
        file: ./racked-website/Dockerfile
        push: true
        tags: ghcr.io/${{ github.actor }}/racked-website:latest
    - name: Build and push bot Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./racked-bot
        file: ./racked-bot/Dockerfile
        push: true
        tags: ghcr.io/${{ github.actor }}/racked-bot:latest

    - name: Build and push docs Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./racked-docs/my-project
        file: ./racked-docs/my-project/Dockerfile
        push: true
        tags: ghcr.io/${{ github.actor }}/racked-docs:latest
        
    - name: Set up Kubeconfig
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'


    - name: Configure kubeconfig
      run: |
        mkdir -p ~/.kube
        echo -n "${{ secrets.KUBECONFIG }}" | base64 --decode > ~/.kube/config
        chmod 600 ~/.kube/config
        kubectl config use-context github-deployer-context

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s-deployment.yaml
        kubectl apply -f k8s-bot-deployment.yaml
        kubectl apply -f k8s-ingress.yaml
        kubectl apply -f k8s-docs-deployment.yaml
        kubectl rollout restart deployment/racked-website
        kubectl rollout restart deployment/racked-bot
        kubectl rollout restart deployment/racked-docs